t=int(input('digite um numero para ver seus multiplos:'))
print('x 1',(t*1))
print('x 2',(t*2))
print('x 3',(t*3))
print('x 4',(t*4))
print('x 5',(t*5))
print('x 6',(t*6))
print('x 7',(t*7))
print('x 8',(t*8))
print('x 9',(t*9))
print('x 10',(t*10))

